services:
  db:
    image: postgres
    restart: always
    ports:
      - "54100:5432"
    environment:
      POSTGRES_USER: clojurians-log
      POSTGRES_PASSWORD: sekrit
      POSTGRES_DB: clojurians-log
